version: "3.5"

services:
  postgres:
    container_name: postgres
    image: debezium/postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=productmanagementdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=master

  # Install Elasticsearch.
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300