package br.com.insurance.market.infra.db;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;

import java.io.Serializable;
import java.util.UUID;

public class QuoteId implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer customerId;
    private UUID quoteId;

    public QuoteId(){}

    public QuoteId(Integer customerId, UUID quoteId){
        this.customerId = customerId;
        this.quoteId = quoteId;
    }


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public Integer getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    @DynamoDBRangeKey
    public UUID getQuoteId() {
        return quoteId;
    }

    public void setQuoteId(UUID quoteId) {
        this.quoteId = quoteId;
    }
}
